-- Conectar na base de dados (assume que já existe)
\c sistema_horarios;

-- Criar tabelas
CREATE TABLE IF NOT EXISTS TIPOUTILIZADOR (
  ID SERIAL PRIMARY KEY,
  TIPOUTILIZADOR VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS UTILIZADOR (
  ID SERIAL PRIMARY KEY,
  NOME VARCHAR(100) UNIQUE NOT NULL,
  EMAIL VARCHAR(100) UNIQUE NOT NULL,
  PASSWORD_HASH VARCHAR(100) NOT NULL,
  TIPO_FUNCIONARIO_ID INT REFERENCES TIPOUTILIZADOR(ID),
  LOJA VARCHAR(100), -- NOVO CAMPO
  CREATED_AT TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS LOJAS (
  ID SERIAL PRIMARY KEY,
  NOME_LOJA VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS HORARIOS (
  ID SERIAL PRIMARY KEY,
  UTILIZADOR_ID INT REFERENCES UTILIZADOR(ID),
  DIA_TRABALHO DATE NOT NULL,
  HORA_ENTRADA TIME NOT NULL,
  HORA_SAIDA TIME NOT NULL,
  HORAS_SEMANAIS INT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT NOW()
);

-- Inserir tipos de utilizador
INSERT INTO TIPOUTILIZADOR (TIPOUTILIZADOR)
VALUES ('ADMINISTRADOR'), ('GERENTE'), ('FUNCIONÁRIO')
ON CONFLICT (TIPOUTILIZADOR) DO NOTHING;

-- Inserir lojas de teste
INSERT INTO LOJAS (NOME_LOJA)
VALUES ('Gelataria Costa Nova'), ('Pizzaria São Bernardo'), ('Gelataria São Bernardo')
ON CONFLICT (NOME_LOJA) DO NOTHING;

-- Inserir utilizadores de teste
INSERT INTO UTILIZADOR (NOME, EMAIL, PASSWORD_HASH, TIPO_FUNCIONARIO_ID, LOJA)
VALUES 
('ADMINISTRADOR', 'admin@sistema.com', '123456', 1, NULL),
('GERENTE_TESTE', 'gerente@sistema.com', '123456', 2, 'Pizzaria São Bernardo'),
('FUNCIONARIO_TESTE', 'funcionario@sistema.com', '123456', 3, 'Gelataria Costa Nova')
ON CONFLICT (NOME) DO NOTHING;

-- Inserir horários de teste
INSERT INTO HORARIOS (UTILIZADOR_ID, DIA_TRABALHO, HORA_ENTRADA, HORA_SAIDA, HORAS_SEMANAIS)
VALUES
(3, '2025-11-06', '09:00', '17:00', 40),
(3, '2025-11-07', '09:00', '17:00', 40),
(2, '2025-11-06', '08:00', '16:00', 40)
ON CONFLICT DO NOTHING;
